{% set name = "mlforecast" %}
{% set version = "0.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mlforecast-{{ version }}.tar.gz
  sha256: cc7e99ea1d08c684bc07bba9e305150967203dfa82e97ebbaa99ffcb174fe992

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numba
    - pandas
    - python >=3.6
    - scikit-learn
    - window-ops

test:
  imports:
    - mlforecast

about:
  home: https://github.com/Nixtla/mlforecast
  dev_url: https://github.com/Nixtla/mlforecast
  doc_url: https://nixtla.github.io/mlforecast/
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  summary: Scalable machine learning based time series forecasting

extra:
  recipe-maintainers:
    - jmoralez
