{% set name = "mlforecast" %}
{% set version = "0.11.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mlforecast-{{ version }}.tar.gz
  sha256: e0b58379bd75650cb0c2ba9b462fb562ea9a21651a4134bfbcbf49dea70a58e8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - coreforecast >=0.0.3
    - numba
    - numpy
    - pandas
    - python >=3.8
    - scikit-learn
    - utilsforecast >=0.0.24
    - window-ops

test:
  imports:
    - mlforecast

about:
  home: https://github.com/Nixtla/mlforecast
  dev_url: https://github.com/Nixtla/mlforecast
  doc_url: https://nixtla.github.io/mlforecast/
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  summary: Scalable machine learning based time series forecasting

extra:
  recipe-maintainers:
    - jmoralez
    - AzulGarza
