{% set name = "mlforecast" %}
{% set version = "0.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mlforecast-{{ version }}.tar.gz
  sha256: c6418f7382bc594eb13ccbd44a688bf9072e15686ff13d8be3bad66d32c9febd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - cloudpickle
    - coreforecast >=0.0.7
    - fsspec
    - numba
    - numpy
    - optuna
    - pandas
    - python >=3.8
    - scikit-learn
    - utilsforecast >=0.0.26
    - window-ops

test:
  imports:
    - mlforecast

about:
  home: https://github.com/Nixtla/mlforecast
  dev_url: https://github.com/Nixtla/mlforecast
  doc_url: https://nixtla.github.io/mlforecast/
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  summary: Scalable machine learning based time series forecasting

extra:
  recipe-maintainers:
    - jmoralez
    - AzulGarza
