{% set name = "mlforecast" %}
{% set version = "0.0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mlforecast-{{ version }}.tar.gz
  sha256: 992149775d2b548c6cf27f42e44b3a9ccfd7c66ac6eeadc555e6e5da02a3691b

build:
  number: 0
  noarch: python
  entry_points:
    - mlforecast=mlforecast.cli:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numba
    - pandas
    - pydantic
    - python >=3.6
    - pyyaml
    - typer
    - window-ops

test:
  imports:
    - mlforecast
  commands:
    - mlforecast --help

about:
  home: https://github.com/Nixtla/mlforecast
  dev_url: https://github.com/Nixtla/mlforecast
  doc_url: https://nixtla.github.io/mlforecast/
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  summary: Scalable machine learning based time series forecasting

extra:
  recipe-maintainers:
    - jose-moralez
