{% set name = "mlforecast" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mlforecast-{{ version }}.tar.gz
  sha256: 152f5c92bc8097e20bb879493a4c1f25b9932f155e3d81d5e1a8b5ada0c74092

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numba
    - pandas
    - python >=3.6
    - window-ops

test:
  imports:
    - mlforecast

about:
  home: https://github.com/Nixtla/mlforecast
  dev_url: https://github.com/Nixtla/mlforecast
  doc_url: https://nixtla.github.io/mlforecast/
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  summary: Scalable machine learning based time series forecasting

extra:
  recipe-maintainers:
    - jmoralez
