{% set name = "mlforecast" %}
{% set version = "0.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mlforecast-{{ version }}.tar.gz
  sha256: 48aecc0c95964203b618510cfeb06457dec2eba3b8c3af41d727766c43a2b4cd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - cloudpickle
    - coreforecast >=0.0.12
    - fsspec
    - numba
    - numpy
    - optuna
    - pandas
    - python >={{ python_min }}
    - scikit-learn
    - utilsforecast >=0.2.3
    - window-ops

test:
  requires:
    - python {{ python_min }}
  imports:
    - mlforecast

about:
  home: https://github.com/Nixtla/mlforecast
  dev_url: https://github.com/Nixtla/mlforecast
  doc_url: https://nixtla.github.io/mlforecast/
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  summary: Scalable machine learning based time series forecasting

extra:
  recipe-maintainers:
    - jmoralez
    - AzulGarza
